// MENSAGENS TOASTR...
$(document).ready(function () {
    const urlParams = new URLSearchParams(window.location.search);

    // FUNÇÃO PARA MSG DE SUCESSO
    function exibeMensagemSucesso($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.success($mensagem, $titulo_mensagem);
        }
    }

    // FUNÇÃO PARA MSG DE ERRO
    function exibeMensagemErro($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.error($mensagem, $titulo_mensagem);
        }
    }

    // FUNÇÃO PARA MSG DE INFORMAÇÃO
    function exibeMensagemInfo($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.info($mensagem, $titulo_mensagem);
        }
    }


// MENSAGENS DE LOGIN...
    // ERRO AO REALIZAR O LOGIN...
    exibeMensagemErro('valida_login', 'valida_login', 'credenciais_invalidas', 'Credenciais inválidas!');
    exibeMensagemErro('valida_login', 'valida_login', 'usuario_desativado', 'Este usuário está desativado!');

// MENSAGENS DE MANIPULAÇÃO DE USUÁRIO...
    // SUCESSO NO CADASTRO DE USUÁRIO...
    exibeMensagemSucesso('usuario', 'usuario', 'cadastrado_com_sucesso', 'Usuário cadastrado com sucesso!');
    // ERRO NO CADASTRO DE USUÁRIO...
    exibeMensagemErro('usuario', 'usuario', 'nome_incompleto', 'O nome deve ser completo.', 'Erro!');
    exibeMensagemErro('usuario', 'usuario', 'usuario_ja_cadastrado', 'Este usuário já está cadastrado.', 'Erro!');
    // SUCESSO NA EDIÇÃO DE USUÁRIO...
    exibeMensagemSucesso('usuario', 'usuario', 'editado_com_sucesso', 'Usuário editado com sucesso!');
    // SUCESSO NA EXCLUSÃO DE USUÁRIO...
    exibeMensagemSucesso('usuario', 'usuario', 'excluido_com_sucesso', 'Usuário excluído com sucesso!');

// MENSAGENS DE MANIPULAÇÃO DE DISPOSITIVO...
    // SUCESSO NO CADASTRO DE DISPOSITIVO...
    exibeMensagemSucesso('dispositivo', 'dispositivo', 'cadastrado', 'Dispositivo cadastrado com sucesso!');
    // SUCESSO NA EDIÇÃO DE DISPOSITIVO...
    exibeMensagemSucesso('dispositivo', 'dispositivo', 'atualizado', 'Dispositivo atualizado com sucesso!');
    // SUCESSO NA EXCLUSÃO DE DISPOSITIVO...
    exibeMensagemSucesso('dispositivo', 'dispositivo', 'excluido', 'Dispositivo excluído com sucesso!');

// MENSAGENS DE BUSCA E FILTRO DE DISPOSITIVOS...
    // SUCESSO NO FILTRO DE LINHAS...
    exibeMensagemSucesso('linhas', 'linhas', '', 'Exibindo linhas cadastradas.');
    // SUCESSO NO FILTRO DE APARELHOS...
    exibeMensagemSucesso('aparelhos', 'aparelhos', '', 'Exibindo aparelhos cadastrados.');
    // SUCESSO NO FILTRO DE APARELHOS COM MDM...
    exibeMensagemSucesso('mdm', 'mdm', '', 'Exibindo aparelhos com MDM.');
    // ERRO AO BUSCAR POR UM VALOR VAZIO...
    exibeMensagemErro('busca', 'busca', 'campo_vazio', 'Preencha com alguma informação do dispositivo.', 'Erro!');

// MENSAGENS DE MANIPULAÇÃO DE OPÇÕES...
    // SUCESSO NO CADASTRO DE OPÇÃO...
    exibeMensagemSucesso('opcao', 'opcao', 'cadastrada', 'Opção cadastrada com sucesso.');
    // SUCESSO NA EDIÇÃO DE OPÇÃO...
    exibeMensagemSucesso('opcao', 'opcao', 'editada', 'Opção editada com sucesso.');
    // SUCESSO NA EXCLUSÃO DE OPÇÃO...
    exibeMensagemSucesso('opcao', 'opcao', 'excluida', 'Opção excluída com sucesso.');
    // ERRO NO CADASTRO DE UMA OPÇÃO JÁ CADASTRADA...
    exibeMensagemErro('opcao', 'opcao', 'ja_cadastrada', 'Essa opção já está cadastrada.', 'Erro!');

// MENSAGENS DE CHAMADOS...
    // SUCESSO NA ABERTURA DE CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'aberto', 'Chamado aberto com sucesso!');
    // SUCESSO NA EDIÇÃO DE CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'atualizado', 'Chamado atualizado com sucesso!');
    // SUCESSO NO FECHAMENTO DE CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'fechado', 'Chamado fechado com sucesso!');
    // SUCESSO AO REABRIR CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'reaberto', 'Chamado reaberto com sucesso!');
    // SUCESSO AO MOVER CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'movido', 'Chamado movido de departamento com sucesso!');
    // SUCESSO AO RESPONDER CHAMADO...
    exibeMensagemSucesso('chamado', 'chamado', 'resposta_enviada', 'Resposta enviada com sucesso!');
    // SUCESSO NA EXCLUSÃO DE RESPOSTA...
    exibeMensagemSucesso('chamado', 'chamado', 'resposta_excluida', 'Resposta excluída com sucesso!');
    // SUCESSO NA ATUALIZAÇÃO DE UMA RESPOSTA...
    exibeMensagemSucesso('chamado', 'chamado', 'resposta_atualizada', 'Resposta atualizada com sucesso!');
    // SUCESSO NA ATUALIZAÇÃO DE UMA RESPOSTA...
    exibeMensagemSucesso('chamado', 'chamado', 'anexo_removido', 'Anexo removido do chamado com sucesso!');

// MENSAGENS DE VALIDAÇÃO DE SENHA...
    // ERRO NA VALIDAÇÃO DO COMPRIMENTO DA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'senha_curta', 'A senha deve conter pelo menos 12 caracteres!', 'Erro!');
    // ERRO NA VALIDAÇÃO DE LETRAS MAIÚSCULAS NA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'letras_maiusculas', 'A senha deve conter pelo menos uma letra maiúscula.', 'Erro!');
    // ERRO NA VALIDAÇÃO DE NÚMEROS NA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'numeros', 'A senha deve conter pelo menos um número.', 'Erro!');
    // ERRO NA VALIDAÇÃO DE CARACTERES ESPECIAIS NA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'caracteres_especiais', 'A senha deve conter pelo menos um caractere especial.', 'Erro!');
    // ERRO NA COMPARAÇÃO DAS SENHAS INFORMADAS...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'desiguais', 'As senhas não conferem!', 'Erro!');
    // SUCESSO NO RESET DA SENHA...
    exibeMensagemSucesso('verifica_senha', 'verifica_senha', 'senha_resetada', 'Senha resetada com sucesso!');
    // SUCESSO NO RESET DA SENHA NO PRIMEIRO ACESSO...
    exibeMensagemSucesso('verifica_senha', 'verifica_senha', 'primeiro_acesso', 'Senha alterada com sucesso! Realize o login com a nova senha para utilizar o sistema.');

// VALIDAÇÃO DE CAMPOS VAZIOS...
    // LINHA...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_linha_vazio', 'O campo da linha deve ser preenchido.', 'Erro!');
    // OPERADORA...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_operadora_vazio', 'O campo da operadora deve ser preenchido.', 'Erro!');
    // STATUS DA LINHA...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_status_vazio', 'O status da linha deve ser informado.', 'Erro!');
    // TIPO DO APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_tipo_vazio', 'O campo do tipo do aparelho deve ser preenchido.', 'Erro!');
    // MARCA DO APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_marca_vazio', 'O campo da marca deve ser preenchido.', 'Erro!');
    // MODELO DO APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_modelo_vazio', 'O campo do modelo deve ser preenchido.', 'Erro!');
    // IMEI DO APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_imei_vazio', 'O campo do IMEI deve ser preenchido.', 'Erro!');
    // IMEI DO APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_mdm_vazio', 'Deve ser informado se o aparelho possui MDM.', 'Erro!');
    // NOME DO USUÁRIO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campo_nome_vazio', 'O campo do nome do usuário deve ser preenchido.', 'Erro!');
    // NOME DO USUÁRIO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'arquivo_invalido', 'O formato do arquivo anexado não é permitido.', 'Erro!');
    // CAMPOS DA LOCALIDADE...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'campos_localidade', 'Todos os campos da localidade são de preenchimento obrigatório.', 'Erro!');
    // TODOS OS CAMPOS...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'todos_campos', 'Todos os campos com um * devem ser preenchidos.', 'Erro!');
    // DISPOSITIVO SEM LINHA OU APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'nenhum_dado', 'Não é possível cadastrar ou atualizar um dispositivo vazio.', 'Erro!');
    // MOTIVO DO FECHAMENTO DE CHAMADO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'motivo_fechamento_vazio', 'O motivo do fechamento é obrigatório.', 'Erro!');
    // RESPOSTA VAZIA EM CHAMADO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'resposta_vazia', 'A resposta deve ser preenchida.', 'Erro!');

// VALIDAÇÃO DE CAMPOS NUMÉRICOS...
    // LINHA...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'linha_nao_numerico', 'O campo da linha deve ser numérico.', 'Erro!');
    // IMEI...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'imei_nao_numerico', 'O campo do IMEI deve ser numérico.', 'Erro!');
    // SIM CARD...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'sim_card_nao_numerico', 'O campo do SIM card deve ser numérico.', 'Erro!');
    // CENTRO DE CUSTOS...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'centro_custo_nao_numerico', 'O campo do centro de custos deve ser numérico.', 'Erro!');
    // MATRÍCULA...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'matricula_nao_numerico', 'O campo da matrícula deve ser numérico.', 'Erro!');

// VALIDAÇÃO DE EMAIL...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'email_invalido', 'O e-mail informado não é válido.', 'Erro!');

// VALIDAÇÃO DE LINHA OU APARELHO...
    exibeMensagemErro('verifica_campo', 'verifica_campo', 'linha_ou_aparelho', 'O cadastro deve possuir uma linha, um aparelho, ou ambos.', 'Erro!');

// MENSAGEM DE ACESSO NEGADO...
    exibeMensagemErro('acesso', 'acesso', 'negado', 'Você não tem permissão para acessar essa página ou executar essa ação.', 'Ops!');

});