

// MENSAGENS TOASTR...
$(document).ready(function () {
    const urlParams = new URLSearchParams(window.location.search);

    // FUNÇÃO PARA MSG DE SUCESSO
    function exibeMensagemSucesso($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.success($mensagem, $titulo_mensagem);
        }
    }

    // FUNÇÃO PARA MSG DE ERRO
    function exibeMensagemErro($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.error($mensagem, $titulo_mensagem);
        }
    }

    // FUNÇÃO PARA MSG DE INFORMAÇÃO
    function exibeMensagemInfo($url1, $url1, $url2, $mensagem, $titulo_mensagem) {

        if (urlParams.has($url1) && urlParams.get($url1) === $url2) {
            toastr.info($mensagem, $titulo_mensagem);
        }
    }

    // MENSAGENS PRODUTOS...
    // SUCESSO NO CADASTRO DE UM PRODUTO...
    exibeMensagemSucesso('cadastra_produto', 'cadastra_produto', 'cadastrado_com_sucesso', 'Produto cadastrado com sucesso!');
    // SUCESSO NA EDIÇÃO DE UM PRODUTO...
    exibeMensagemSucesso('edita_produto', 'edita_produto', 'editado_com_sucesso', 'Produto editado com sucesso!');
    // SUCESSO NA EXCLUSÃO DE UM PRODUTO...
    exibeMensagemSucesso('exclui_produto', 'exclui_produto', 'excluido_com_com_sucesso', 'Produto excluido com sucesso!');


    // MENSAGENS REQUISIÇÃO...
    // SUCESSO NA ABERTURA DE UMA REQUISIÇÃO...
    exibeMensagemSucesso('abre_requisicao', 'abre_requisicao', 'aberta_com_sucesso', '<a href="inicio.php">Caso necessário, apresente o Nº da requisição ao almoxarifado.<br><br>Clique para visualizar suas requisições em aberto ou acesse a página inicial.</a>', '<a href="inicio.php">Requisição realizada com sucesso!<br><br></a>');
    // ERRO NA COMPARAÇÃO ENTRE ESTOQUE E ESTOQUE MÍNIMO...
    exibeMensagemErro('erro_requisicao', 'erro_requisicao', 'quantidade_invalida', 'A quantidade solicitada deve ser menor que a quantidade disponível em estoque!', 'Requisição não aberta!')
    // INFORMAÇÃO AO RECUSAR UMA REQUISICÃO...
    exibeMensagemInfo('recusa_requisicao', 'recusa_requisicao', 'requisicao_recusada', 'Requisição recusada e devolvida ao estoque!');
    // SUCESSO NA ENTREGA DE UMA REQUISIÇÃO...
    exibeMensagemSucesso('entrega_requisicao', 'entrega_requisicao', 'requisicao_entregue', 'Requisição entregue com sucesso!');
    // INFORMAÇÃO AO CANCELAR UMA REQUISICÃO...
    exibeMensagemSucesso('cancela_requisicao', 'cancela_requisicao', 'requisicao_cancelada', 'Sua requisição foi cancelada com sucesso!');

    //MENSAGEM LOGIN...
    // ERRO AO REALIZAR O LOGIN...
    exibeMensagemErro('valida_login', 'valida_login', 'credenciais_invalidas', 'Credenciais inválidas!');
    // ERRO AO REALIZAR O LOGIN...
    exibeMensagemErro('valida_login', 'valida_login', 'usuario_desativado', 'Esse usuário está desativado!');


    // MENSAGENS DE MANIPULAÇÃO DE USUÁRIO...
    // SUCESSO NO CADASTRO DE UM USUÁRIO...
    exibeMensagemSucesso('cadastra_usuario', 'cadastra_usuario', 'cadastrado_com_sucesso', 'Usuário cadastrado com sucesso!');
    // ERRO NO CADASTRO DE UM USUÁRIO...
    exibeMensagemErro('verifica_cadastro', 'verifica_cadastro', 'erro_no_cadastro', 'O nome deve ser completo.', "Usuário não criado!");
    // ERRO NO CADASTRO DE UM USUÁRIO...
    exibeMensagemErro('verifica_cadastro', 'verifica_cadastro', 'usuario_ja_cadastrado', 'Esse usuário já está cadastrado.', "Usuário não criado!");
    // SUCESSO NA EDIÇÃO DE UM USUÁRIO...
    exibeMensagemSucesso('edita_usuario', 'edita_usuario', 'editado_com_sucesso', 'Usuário editado com sucesso!');
    // SUCESSO NA EXCLUSÃO DE UM USUÁRIO...
    exibeMensagemSucesso('exclui_usuario', 'exclui_usuario', 'excluido_com_sucesso', "<br>Todas as requisições desse usuário foram excluídas do histórico.", 'Usuário excluido com sucesso!');
    // ERRO NA EXCLUSÃO DE UM USUÁRIO...
    exibeMensagemErro('exclui_usuario', 'exclui_usuario', 'erro_na_exclusao', '<a href="../gerenciar_requisicoes.php"><br>Esse usuário possui requisições em aberto.<br>Entregue ou cancele essas requisições antes de exclui-lo.<br><br>Clique para exibir todas as requisições em aberto</a>', '<a href="../gerenciar_requisicoes.php">Não foi possível excluir esse usuário!</a>');


    // MENSAGEM DE VALIDAÇÃO DE CAMPOS...
    // ERRO DE CAMPOS NÃO PREENCHIDOS...
    exibeMensagemErro('verifica_campos', 'verifica_campos', 'campos_nao_preenchidos', 'Os campos obrigatórios possuem um * vermelho', 'Preencha todos os campos obrigatorios!');
    // ERRO AO FORNECER UM NÚMERO NEGATIVO...
    exibeMensagemErro('verifica_campos', 'verifica_campos', 'numero_negativo', 'Um ou mais campos estão com valor negativo.', 'Erro!');
    // ERRO AO FORNECER UM VALOR NÃO NUMÉRICO...
    exibeMensagemErro('verifica_campos', 'verifica_campos', 'nao_numerico', 'Um ou mais campos estão com valor não numérico.', 'Erro!');


    // MENSAGENS DE VALIDAÇÃO DE SENHA...
    // ERRO NA VALIDAÇÃO DO COMPRIEMENTO DA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'senha_curta', 'O nome deve ser completo!', 'A senha deve conter pelo menos 12 caracteres!', "Erro na validação da senha!");
    // ERRO NA VALIDAÇÃO DE LETRAS MAIUSCULAS NA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'letras_maiusculas', 'O nome deve ser completo!', 'A senha deve conter pelo menos uma letra maiúscula', "Erro na validação da senha!");
    // ERRO NA VALIDAÇÃO DE NÚMEROS NA SENHA INFORMADA...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'numeros', 'O nome deve ser completo!', 'A senha deve conter pelo menos um número', "Erro na validação da senha!");
    // ERRO NA VALIDAÇÃO DE COMPARAÇÃO DAS DUAS SENHAS INFORMADAS...
    exibeMensagemErro('verifica_senha', 'verifica_senha', 'desiguais', 'O nome deve ser completo!', 'As senhas não conferem!', "Erro na validação da senha!");
    // SUCESSO NO RESET DA SENHA...
    exibeMensagemSucesso('verifica_senha', 'verifica_senha', 'senha_resetada', 'Senha resetada com sucesso!');
    // SUCESSO NO RESET DA SENHA DO PRIMEIRO ACESSO...
    exibeMensagemSucesso('verifica_senha', 'verifica_senha', 'primeiro_acesso', '<br>Agora realize o login com a nova senha e começe a utilizar o sistema!', 'Senha alterada com sucesso!');


    // MENSAGENS PARA INVENTÁRIO...
    // SUCESSO AO CRIAR UM INVENTÁRIO...
    exibeMensagemSucesso('inventario', 'inventario', 'inventario_criado', 'Inventário criado com sucesso!');
    // ERRO AO CRIAR UM INVENTÁRIO...
    exibeMensagemErro('inventario', 'inventario', 'inventario_nao_criado', 'Existe um inventário em aberto, finalize-o antes de criar outro.', 'Inventário não criado!<br><br>');
    // SUCESSO AOR INVENTARIAR UM PRODUTO...
    exibeMensagemSucesso('inventario', 'inventario', 'produto_inventariado', 'O saldo do estoque desse produto foi atualizado para o valor informado.', 'Produto inventariado com sucesso!<br><br>');
    // ERRO AO INVENTARIAR UM PRODUTO...
    exibeMensagemErro('inventario', 'inventario', 'valor_invalido', 'O valor contado da quantidade deve ser numérico!', 'Produto não inventariado!<br><br>');
    // SUCESSO AO FINALIZAR UM INVENTÁRIO...
    exibeMensagemSucesso('inventario', 'inventario', 'inventario_finalizado', 'Inventário finalizado com sucesso!');
    // ERRO AO FINALIZAR UM INVENTÁRIO...
    exibeMensagemErro('inventario', 'inventario', 'inventario_nao_finalizado', 'Existe um ou mais produtos não inventariados!', 'Inventário não finalizado!<br><br>');
    // SUCESSO AO EXCLUIR UM INVENTÁRIO...
    exibeMensagemSucesso('inventario', 'inventario', 'inventario_excluido', 'Inventário excluído com sucesso!');

});