<?php

// CONEXÃO COM O BANCO DE DADOS...
// Extensão usada para conexão com o banco de dados: PDO...
// Sistema de banco de dados utilizado como padrão: MySQL...
    $pdo = new PDO("mysql:host=localhost; dbname=telefonia; charset=utf8mb4", "root", "root");
    $pdo->query("SET lc_time_names = 'PT_BR'"); // Define o padrão de data para o padrão brasileiro, utilizado nas consultas SQL onde é retornado uma data...
//==========================================================================